routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', 'HomeController@index')->middleware('guest');
Route::get('faq', 'HomeController@faq')->name('faq');

Route::get('article/{article}', 'HomeController@show')->name('article.show');
Route::post('article/{article}/comment', 'CommentController@store')->middleware('auth')->name('comment.store');

Route::group(['prefix' => 'admin', 'middleware' => 'checkAdmin'], function () {
    Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
    Route::get('settings', 'HomeController@settings')->name('settings')->middleware('can:settings-admin');
    Route::get('statistics', 'HomeController@statistics')->name('statistics');
    Route::post('settings', 'HomeController@settingsStore')->name('settings.store')->middleware('can:settings-admin');

    Route::resource('roles' , 'RoleController');
    Route::resource('books', 'BookController');
    Route::get('book-categories', 'BookCategoryController@index')->name('book-categories.index');
    Route::post('book-categories', 'BookCategoryController@store')->name('book-categories.store');
    Route::delete('book-categories', 'BookCategoryController@destroy')->name('book-categories.destroy');
    Route::patch('book-categories', 'BookCategoryController@update')->name('book-categories.update');
    Route::resource('articles', 'ArticleController');
    Route::get('articles/comments/index', 'ArticleController@comments')->name('articles.comments');
    Route::resource('users', 'UserController');

    Route::group(['prefix' => 'users'], function () {
        Route::get('new/index', 'UserController@newUsers')->name('users.new');
        Route::get('{user}/confirm', 'UserController@confirm')->name('users.confirm');
    });

    Route::get('user-search', 'UserController@search')->name('users.search');

    Route::group(['prefix' => 'lends', 'middleware' => 'can:lends-admin'], function () {
        Route::get('admin', 'LendController@admin')->name('lends.admin');
        Route::post('user-active-lends', 'LendController@userActiveLends')->name('lends.userActiveLends');
        Route::get('{user}/lends-history', 'LendController@lendsHistory')->name('users.lendsHistory');
        Route::get('{user}/active-lends', 'LendController@activeLends')->name('users.activeLends');
        Route::get('all-active-lends', 'LendController@allActiveLends')->name('lends.allActiveLends');

        Route::post('create', 'LendController@create')->name('lends.create');
        Route::get('extend/{lend}', 'LendController@extendLend')->name('lends.extend');
        Route::get('return/{lend}', 'LendController@returnLend')->name('lends.return');
    });
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth:web'], function () {
    Route::get('profile', 'HomeController@profile')->name('profile');
    Route::get('lends/my-active-lends', 'HomeController@myActiveLends')->name('lends.myActiveLends');
    Route::get('lends/my-lends-history', 'HomeController@myLendsHistory')->name('lends.myLendsHistory');
    Route::get('lends/extend-my-lend/{lend}', 'HomeController@extendMyLend')->name('lends.extendMyLend');
    Route::get('faq', 'HomeController@faq_admin')->name('admin-faq');

    Route::get('book-search', 'HomeController@bookSearch')->name('books.search');
});

app/Article.php
<?php

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $guarded = [];

    use sluggable;

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function getCreatedAtAttribute($value)
    {
        return jDate($value)->format('%d %B %Y');
    }

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\Comment;

class ArticleController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:articles-admin');
    }

    public function index()
    {
        $articles = Article::latest()->paginate(10);
        return view('admin.article.index', compact('articles'));
    }

    public function comments()
    {
        $comments = Comment::latest()->get();
        return view('admin.article.comments', compact('comments'));
    }

    public function create()
    {
        return view('admin.article.create');
    }

    public function store()
    {
        $this->validation();

        auth()->user()->articles()->create([
            'title' => request('title'),
            'body' => request('body'),
            'status' => request('status'),
        ]);

        session()->flash('message', 'نوشته با موفقیت ایجاد شد.');
        return redirect('admin/articles');
    }

    public function update(Article $article)
    {
        $this->validation();

        $article->update([
            'title' => request('title'),
            'body' => request('body'),
            'status' => request('status'),
        ]);

        session()->flash('message', 'نوشته با موفقیت بروزرسانی شد.');
        return redirect(route('articles.edit', ['article' => $article->slug]));
    }

    public function destroy(Article $article)
    {
        $article->delete();

        session()->flash('message', 'نوشته با موفقیت حذف شد.');
        return redirect('admin/articles');
    }

    public function edit(Article $article)
    {
        return view('admin.article.edit', compact('article'));
    }

    private function validation()
    {
        $this->validate(request(), [
            'title' => 'required',
            'body' => 'required',
            'status' => 'required',
        ], [
            'title.required' => 'لطفا عنوان نوشته را وارد کنید',
            'body.required' => 'لطفا متن نوشته را وارد کنید',
            'status.required' => 'لطفا حالت نوشته را انتخاب کنید',
        ]);
    }
}

resources/views/admin/article/comments.blade.php
@extends('admin.layouts.master', ['title' => 'دیدگاه ها'])

@section('content')

    <!-- Page Header -->
    <div class="content-header">
        <div class="row">
            <div class="col-sm-6">
                <div class="header-section">
                    <h1>دیدگاه ها</h1>
                </div>
            </div>
            <div class="col-sm-6 hidden-xs">
                <div class="header-section">
                    <ul class="breadcrumb breadcrumb-top">
                        <li>مدیریت نوشته ها</li>
                        <li>دیدگاه ها</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- END Page Header -->

    @if($comments->isEmpty())
        <div class="block full">
            <!-- Get Started Content -->
            دیدگاه ها خالی است.
            <!-- END Get Started Content -->
        </div>
    @else

        <div class="row">
            <div class="col-lg-12">
                <!-- Timeline Block -->
                <div class="block">
                    <!-- Timeline Title -->
                    <div class="block-title">
                        <h2>دیدگاه ها</h2>
                    </div>
                    <!-- END Timeline Title -->

                    <!-- Timeline Content -->
                    <div class="timeline block-content-full">
                        <ul class="timeline-list">
                            @foreach($comments as $comment)
                                <li>
                                    <div class="timeline-time">{{ jdate($comment->created_at)->ago() }}</div>
                                    <img class="img-thumbnail-transparent timeline-icon" src="{{ $comment->user->getImage }}" />
                                    <div class="timeline-content">
                                        <p class="push-bit small">
                                            <a target="_blank" @can('users-admin') href="{{ route('users.show', ['user' => $comment->user->id]) }}" @endcan>{{ $comment->user->fullname }}</a> در <a target="_blank" href="{{ route('article.show', ['article' => $comment->article->slug]) }}">{{ $comment->article->title }}</a>
                                        </p>
                                        <p>{{ $comment->body }}</p>
                                    </div>
                                </li>
                            @endforeach
                        </ul>
                    </div>
                    <!-- END Timeline Content -->
                </div>
                <!-- END Timeline Block -->
            </div>
        </div>
    @endif

@endsection

resources/views/admin/article/create.blade.php
@extends('admin.layouts.master', ['title' => 'افزودن نوشته جدید'])

@section('content')
    <!-- Page Header -->
    <div class="content-header">
        <div class="row">
            <div class="col-sm-6">
                <div class="header-section">
                    <h1>افزودن نوشته جدید</h1>
                </div>
            </div>
            <div class="col-sm-6 hidden-xs">
                <div class="header-section">
                    <ul class="breadcrumb breadcrumb-top">
                        <li>مدیریت نوشته ها</li>
                        <li>افزودن نوشته جدید</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- END Page Header -->

    @include('admin.layouts.errors')
    @include('admin.layouts.messages')

    <!-- Form Validation Content -->
    <div class="row">
        <div class="col-md-12">
            <div class="block">
                <!-- CKEditor Title -->
                <div class="block-title">
                    <h2>افزودن نوشته</h2>
                </div>
                <!-- END CKEditor Title -->

                <!-- CKEditor Content -->
                <form action="{{ route('articles.store') }}" method="post" class="form-horizontal">
                    {!! csrf_field() !!}

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="text" id="title" name="title" class="form-control" placeholder="عنوان نوشته" value="{{ old('title') }}">
                        </div>
                    </div>

                    <fieldset>
                        <div class="form-group">
                            <div class="col-md-12">
                                <textarea id="textarea-ckeditor" name="body" class="ckeditor" style="visibility: hidden; display: none;">{!! old('body') !!}</textarea>
                            </div>
                        </div>
                    </fieldset>
                    <div class="form-group form-actions">
                        <div class="col-xs-12">
                            <div class="col-md-2 col-xs-4">
                                <select name="status" class="form-control">
                                    <option value="publish" selected>انتشار</option>
                                    <option value="draft">پیش نویس</option>
                                </select>
                            </div>
                            <div class="col-xs-6">
                                <button type="submit" class="btn btn-effect-ripple btn-primary" style="overflow: hidden; position: relative;">ذخیره</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- END Form Validation Content -->

@endsection

@section('scripts')
    <script src="/js/plugins/ckeditor/ckeditor.js"></script>
@endsection

resources/views/admin/article/edit.blade.php
@extends('admin.layouts.master', ['title' => 'ویرایش نوشته'])

@section('content')
    <!-- Form Validation Content -->
    <div class="row">
        <div class="col-md-12">
            <div class="block">
                <!-- CKEditor Title -->
                <div class="block-title">

                    <h2>ویرایش نوشته</h2>
                </div>
                <!-- END CKEditor Title -->

                <!-- CKEditor Content -->
                <form action="{{ route('articles.update', ['article' => $article->slug]) }}" method="post" class="form-horizontal">
                    {!! csrf_field() !!}
                    {{ method_field('PATCH') }}

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="text" id="title" name="title" class="form-control" placeholder="عنوان نوشته" value="{{ $article->title }}">
                        </div>

                    </div>

                    <fieldset>
                        <div class="form-group">
                            <div class="col-md-12">
                                <textarea id="textarea-ckeditor" name="body" class="ckeditor" style="visibility: hidden; display: none;">{!! $article->body !!}</textarea>
                            </div>
                        </div>
                    </fieldset>
                    <div class="form-group form-actions">
                        <div class="col-xs-12">
                            <div class="col-md-2">
                                <select name="status" class="form-control">
                                    <option value="publish" @if($article->status == 'publish') selected @endif>انتشار</option>
                                    <option value="draft" @if($article->status == 'draft') selected @endif>پیش نویس</option>
                                </select>
                            </div>
                            <input type="hidden" name="submit">
                            <button type="submit" class="btn btn-effect-ripple btn-primary" style="overflow: hidden; position: relative;">ذخیره</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- END Form Validation Content -->
    @include('admin.layouts.errors')
    @include('admin.layouts.messages')

@endsection

@section('scripts')
    <script src="/js/plugins/ckeditor/ckeditor.js"></script>
@endsection

resources/views/admin/article/index.blade.php
@extends('admin.layouts.master', ['title' => 'نوشته ها'])

@section('content')
    <!-- Page Header -->
    <div class="content-header">
        <div class="row">
            <div class="col-sm-6">
                <div class="header-section">
                    <h1>نوشته ها</h1>
                </div>
            </div>
            <div class="col-sm-6 hidden-xs">
                <div class="header-section">
                    <ul class="breadcrumb breadcrumb-top">
                        <li>مدیریت نوشته ها</li>
                        <li>نوشته ها</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- END Page Header -->

    @if($articles->isEmpty())

        <div class="block full">
            <!-- Get Started Content -->
            لیست نوشته ها خالی است.
            <!-- END Get Started Content -->
        </div>

    @else

        <div class="row">
            <div class="col-md-12 col-lg-12">
                <!-- Tickets Block -->
                <div class="block">
                    <!-- Tickets List -->
                    <div class="table-responsive">

                        <table class="table table-hover table-vcenter table-borderless">
                            <thead>
                                <tr>
                                    <th>عنوان</th>
                                    <th>نویسنده</th>
                                    <th class="text-center">تاریخ انتشار</th>
                                    <th class="text-center"><i class="fa fa-comments"></i></th>
                                    <th class="text-center">وضعیت</th>

                                    <th style="width: 80px;" class="text-center"><i class="fa fa-flash"></i></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($articles as $article)
                                    <tr>
                                        <td><a href="{{ route('article.show', ['article' => $article->slug]) }}" target="_blank"><strong>{{ $article->title }}</strong></a></td>

                                        <td>{{ $article->user->firstName.' '.$article->user->lastName }}</td>

                                        <td class="text-center">{{ $article->created_at }}</td>

                                        <td class="text-center"><span class="badge">{{ $article->comments->count() }}</span></td>
                                        @if($article->status == 'publish')
                                            <td class="text-center"><span class="label label-success">منتشر شده</span></td>
                                        @else
                                            <td class="text-center"><span class="label label-danger">پیش نویس</span></td>
                                        @endif
                                        <td class="text-center">
                                            <a href="{{ route('articles.edit', ['article' => $article->slug]) }}" title="ویرایش" class="btn btn-effect-ripple btn-xs btn-success" style="overflow: hidden; position: relative;"><i class="fa fa-pencil"></i></a>
                                            <a onclick="document.getElementById('deleteForm').action='{{ route('articles.destroy', ['article' => $article->slug]) }}'" href="#modal-fade" data-toggle="modal" title="حذف" class="btn btn-effect-ripple btn-xs btn-danger" style="overflow: hidden; position: relative;"><i class="fa fa-times"></i></a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <form action="#" id="deleteForm" method="post">
                        {!! csrf_field() !!}
                        {{ method_field('DELETE') }}
                    </form>

                    <div id="modal-fade" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                    <h3 class="modal-title"><strong>هشدار</strong></h3>
                                </div>
                                <div class="modal-body">
                                    آیا میخواهید این پست را حذف کنید؟
                                </div>
                                <div class="modal-footer">
                                    <button onclick="document.getElementById('deleteForm').submit();" type="button" class="btn btn-effect-ripple btn-danger" style="overflow: hidden; position: relative;">بله</button>
                                    <button type="button" class="btn btn-effect-ripple btn-success" data-dismiss="modal" style="overflow: hidden; position: relative;">خیر</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="text-center">
                        {!! $articles->render() !!}
                    </div>

                </div>
                <!-- END Tickets Block -->
                @include('admin.layouts.messages')
            </div>
        </div>

    @endif

@endsection