routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', 'HomeController@index')->middleware('guest');
Route::get('faq', 'HomeController@faq')->name('faq');

Route::get('article/{article}', 'HomeController@show')->name('article.show');
Route::post('article/{article}/comment', 'CommentController@store')->middleware('auth')->name('comment.store');

Route::group(['prefix' => 'admin', 'middleware' => 'checkAdmin'], function () {
    Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
    Route::get('settings', 'HomeController@settings')->name('settings')->middleware('can:settings-admin');
    Route::get('statistics', 'HomeController@statistics')->name('statistics');
    Route::post('settings', 'HomeController@settingsStore')->name('settings.store')->middleware('can:settings-admin');

    Route::resource('roles' , 'RoleController');
    Route::resource('books', 'BookController');
    Route::get('book-categories', 'BookCategoryController@index')->name('book-categories.index');
    Route::post('book-categories', 'BookCategoryController@store')->name('book-categories.store');
    Route::delete('book-categories', 'BookCategoryController@destroy')->name('book-categories.destroy');
    Route::patch('book-categories', 'BookCategoryController@update')->name('book-categories.update');
    Route::resource('articles', 'ArticleController');
    Route::get('articles/comments/index', 'ArticleController@comments')->name('articles.comments');
    Route::resource('users', 'UserController');

    Route::group(['prefix' => 'users'], function () {
        Route::get('new/index', 'UserController@newUsers')->name('users.new');
        Route::get('{user}/confirm', 'UserController@confirm')->name('users.confirm');
    });

    Route::get('user-search', 'UserController@search')->name('users.search');

    Route::group(['prefix' => 'lends', 'middleware' => 'can:lends-admin'], function () {
        Route::get('admin', 'LendController@admin')->name('lends.admin');
        Route::post('user-active-lends', 'LendController@userActiveLends')->name('lends.userActiveLends');
        Route::get('{user}/lends-history', 'LendController@lendsHistory')->name('users.lendsHistory');
        Route::get('{user}/active-lends', 'LendController@activeLends')->name('users.activeLends');
        Route::get('all-active-lends', 'LendController@allActiveLends')->name('lends.allActiveLends');

        Route::post('create', 'LendController@create')->name('lends.create');
        Route::get('extend/{lend}', 'LendController@extendLend')->name('lends.extend');
        Route::get('return/{lend}', 'LendController@returnLend')->name('lends.return');
    });
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth:web'], function () {
    Route::get('profile', 'HomeController@profile')->name('profile');
    Route::get('lends/my-active-lends', 'HomeController@myActiveLends')->name('lends.myActiveLends');
    Route::get('lends/my-lends-history', 'HomeController@myLendsHistory')->name('lends.myLendsHistory');
    Route::get('lends/extend-my-lend/{lend}', 'HomeController@extendMyLend')->name('lends.extendMyLend');
    Route::get('faq', 'HomeController@faq_admin')->name('admin-faq');

    Route::get('book-search', 'HomeController@bookSearch')->name('books.search');
});

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $guarded = [];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(BookCategory::class, 'category_id', 'id');
    }

    public function scopeSearch($query, $keyword)
    {
        $query->whereHas('category', function ($query) use ($keyword) {
            $query->where('name', $keyword);
        })
            ->orWhere('name', $keyword)
            ->orWhere('name', 'LIKE', $keyword . ' %')
            ->orWhere('name', 'LIKE', '% ' . $keyword)
            ->orWhere('name', 'LIKE', '% ' . $keyword . ' %')
            ->orWhere('author', $keyword)
            ->orWhere('author', 'LIKE', $keyword . ' %')
            ->orWhere('author', 'LIKE', '% ' . $keyword)
            ->orWhere('author', 'LIKE', '% ' . $keyword . ' %')
            ->orWhere('bookmaker', $keyword);
        return $query;
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Book;

class BookController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:books-admin');
    }

    public function create()
    {
        return view('admin.book.create');
    }

    public function edit(Book $book)
    {
        return view('admin.book.edit', compact('book'));
    }

    public function show(Book $book)
    {
        return view('admin.book.show', compact('book'));
    }

    public function destroy(Book $book)
    {
        $book->delete();
        session()->flash('message', 'کتاب با موفقیت حذف شد.');
        return redirect(route('books.index'));
    }

    public function update(Book $book)
    {
        $this->validation();

        $book->update([
            'name' => request('bookName'),
            'author' => request('author'),
            'bookmaker' => request('bookmaker'),
            'count' => request('count'),
            'ed_year' => request('ed_year'),
            'description' => request('description'),
            'category_id' => request('category'),
        ]);

        session()->flash('message', 'اطلاعات کتاب با موفقیت بروزرسانی شد.');

        return redirect(route('books.index'));
    }

    public function index()
    {
        $books = Book::get();
        return view('admin.book.index', compact('books'));
    }

    public function store()
    {
        $this->validation();

        auth()->user()->books()->create([
            'name' => request('bookName'),
            'author' => request('author'),
            'bookmaker' => request('bookmaker'),
            'count' => request('count'),
            'ed_year' => request('ed_year'),
            'description' => request('description'),
            'category_id' => request('category'),
        ]);

        session()->flash('message', 'کتاب با موفقیت اضافه شد');

        return back();
    }

    private function validation()
    {
        $this->validate(request(), [
            'bookName' => 'required',
            'author' => 'required',
            'bookmaker' => 'required',
            'count' => 'required',
            'category' => 'required|exists:book_categories,id',
            'ed_year' => 'required',

        ], [
            'bookName.required' => 'لطفا نام کتاب را وارد کنید',
            'author.required' => 'لطفا نام نویسنده را وارد کنید',
            'bookmaker.required' => 'لطفا نام انتشارات کتاب را وارد کنید',
            'count.required' => 'لطفا تعداد کتاب را وارد کنید',
            'category.required' => 'لطفا دسته بندی را انتخاب کنید',
            'category.exists' => 'دسته بندی وارد شده موجود نیست',
            'ed_year.required' => 'لطفا سال چاپ را وارد کنید',
        ]);
    }
}

resources/views/admin/book/create.blade.php
@extends('admin.layouts.master', ['title' => 'افزودن کتاب جدید'])

@section('content')
    <!-- Blank Header -->
    <div class="content-header">
        <div class="row">
            <div class="col-sm-6">
                <div class="header-section">
                    <h1>افزودن کتاب جدید</h1>
                </div>
            </div>
            <div class="col-sm-6 hidden-xs">
                <div class="header-section">
                    <ul class="breadcrumb breadcrumb-top">
                        <li>مدیریت کتاب ها</li>
                        <li>افزودن کتاب جدید</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- END Blank Header -->
    <!-- Form Validation Content -->
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">

            @include('admin.layouts.errors')
            @include('admin.layouts.messages')

            <!-- Form Validation Block -->
            <div class="block">
                <!-- Form Validation Title -->
                <div class="block-title">
                    <h2>افزودن کتاب جدید</h2>
                </div>
                <!-- END Form Validation Title -->

                <!-- Form Validation Form -->
                <form action="{{ route('books.store') }}" id="form-validation"  method="post" class="form-horizontal form-bordered">
                    {!! csrf_field() !!}

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="val-bookname">نام کتاب <span class="text-danger">*</span></label>
                        <div class="col-md-7">
                            <input type="text" id="val-bookname" name="bookName" class="form-control" value="{{ old('bookName') }}" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="val-author">نویسنده <span class="text-danger">*</span></label>
                        <div class="col-md-7">
                            <input type="text" id="val-author" name="author" class="form-control" value="{{ old('author') }}" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="val-bookmaker">ناشر <span class="text-danger">*</span></label>
                        <div class="col-md-7">
                            <input type="text" id="val-bookmaker" name="bookmaker" class="form-control" value="{{ old('bookmaker') }}" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="range">تعداد <span class="text-danger">*</span></label>
                        <div class="col-md-7">
                            <input type="number" id="val-range" name="count" class="form-control" value="{{ old('count') }}" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="val-category">دسته <span class="text-danger">*</span></label>
                        <div class="col-md-7">
                            <select id="val-category" name="category" class="form-control">
                                <option value="">لطفا انتخاب کنید</option>
                                @foreach(\App\BookCategory::all() as $category)
                                <option value="{{ $category->id }}" @if(old('category') == $category->id) selected @endif>{{ $category->name }}</option>
                                @endforeach

                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="val-ed_year">سال چاپ <span class="text-danger">*</span></label>
                        <div class="col-md-7">
                            <input type="text" id="val-ed_year" name="ed_year" class="form-control" value="{{ old('ed_year') }}" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="val-description">توضیحات </label>
                        <div class="col-md-9">
                            <textarea id="val-description" name="description" rows="7" class="form-control" >{{ old('description') }}</textarea>
                        </div>
                    </div>

                    <div class="form-group form-actions">
                        <div class="col-md-8 col-md-offset-3">
                            <button type="submit" class="btn btn-effect-ripple btn-primary">ذخیره</button>
                            <button type="reset" class="btn btn-effect-ripple btn-danger">تازه کردن</button>
                        </div>
                    </div>
                    <input type="hidden" name="submit" />
                </form>
                <!-- END Form Validation Form -->

            </div>
        <!-- END Form Validation Block -->

        </div>
    </div>
    <!-- END Form Validation Content -->

@endsection

@section('scripts')
    <script src="/js/pages/bookCreate.js"></script>
    <script>$(function(){ FormsValidation.init(); });</script>
@endsection

resources/views/admin/book/edit.blade.php
@extends('admin.layouts.master', ['title' => 'ویرایش کتاب'])

@section('content')

    <!-- Form Validation Content -->
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">

            @include('admin.layouts.errors')
            @include('admin.layouts.messages')

            <!-- Form Validation Block -->
            <div class="block">
                <!-- Form Validation Title -->
                <div class="block-title">
                    <h2>ویرایش کتاب</h2>
                </div>
                <!-- END Form Validation Title -->

                <!-- Form Validation Form -->
                <form action="{{ route('books.update', ['book' => $book]) }}" id="form-validation"  method="post" class="form-horizontal form-bordered">
                    {!! csrf_field() !!}
                    {{ method_field('PATCH') }}

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="val-bookname">نام کتاب <span class="text-danger">*</span></label>
                        <div class="col-md-6">
                            <input type="text" id="val-bookname" name="bookName" class="form-control" value="{{ $book->name }}" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="val-author">نویسنده <span class="text-danger">*</span></label>
                        <div class="col-md-6">
                            <input type="text" id="val-author" name="author" class="form-control" value="{{ $book->author }}" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="val-bookmaker">ناشر <span class="text-danger">*</span></label>
                        <div class="col-md-6">
                            <input type="text" id="val-bookmaker" name="bookmaker" class="form-control" value="{{ $book->bookmaker }}" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="range">تعداد <span class="text-danger">*</span></label>
                        <div class="col-md-6">
                            <input type="number" id="val-range" name="count" class="form-control" value="{{ $book->count }}" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="val-category">دسته <span class="text-danger">*</span></label>
                        <div class="col-md-6">
                            <select id="val-category" name="category" class="form-control">
                                <option value="">لطفا انتخاب کنید</option>
                                @foreach(\App\BookCategory::all() as $category)
                                    <option value="{{ $category->id }}" @if($book->category_id == $category->id) selected @endif>{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="val-ed_year">سال چاپ <span class="text-danger">*</span></label>
                        <div class="col-md-6">
                            <input type="text" id="val-ed_year" name="ed_year" class="form-control" value="{{ $book->ed_year }}" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="val-description">توضیحات </label>
                        <div class="col-md-9">
                            <textarea id="val-description" name="description" rows="7" class="form-control" >{{ $book->description }}</textarea>
                        </div>
                    </div>

                    <div class="form-group form-actions">
                        <div class="col-md-8 col-md-offset-3">
                            <button type="submit" class="btn btn-effect-ripple btn-primary">ذخیره</button>
                            <button type="reset" class="btn btn-effect-ripple btn-danger">تازه کردن</button>
                        </div>
                    </div>
                    <input type="hidden" name="submit" />
                </form>
                <!-- END Form Validation Form -->

            </div>
            <!-- END Form Validation Block -->

        </div>
    </div>
    <!-- END Form Validation Content -->

@endsection

@section('scripts')
    <script src="/js/pages/bookCreate.js"></script>
    <script>$(function(){ FormsValidation.init(); });</script>
@endsection

resources/views/admin/book/index.blade.php
@extends('admin.layouts.master', ['title' => 'لیست کتاب ها'])

@section('content')
    <!-- Blank Header -->
    <div class="content-header">
        <div class="row">
            <div class="col-sm-6">
                <div class="header-section">
                    <h1>لیست کتاب ها</h1>
                </div>
            </div>
            <div class="col-sm-6 hidden-xs">
                <div class="header-section">
                    <ul class="breadcrumb breadcrumb-top">
                        <li>مدیریت کتاب ها</li>
                        <li>لیست کتاب ها</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- END Blank Header -->

    @if($books->isEmpty())
        <div class="block full">
            <!-- Get Started Content -->
            لیست کتاب ها خالی است.
            <!-- END Get Started Content -->
        </div>
    @else
        <div class="row">
            <div class="col-lg-12">
                @include('admin.layouts.messages')
                
                <!-- Row Styles Block -->
                <div class="block">
                    <!-- Row Styles Content -->
                    <div class="table-responsive">
                        <table class="table table-borderless table-vcenter table-hover">
                            <thead>
                                <tr>
                                    <th class="text-center" style="width: 50px;">ID</th>
                                    <th>نام کتاب</th>
                                    <th>نویسنده</th>
                                    <th>ناشر</th>
                                    <th>سال چاپ</th>
                                    <th class="text-center">وضعیت</th>
                                    <th style="width: 80px;" class="text-center"><i class="fa fa-flash"></i></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($books as $book)
                                    <tr>
                                        <td class="text-center">{{ $book->id }}</td>
                                        <td><strong>{{ $book->name }}</strong></td>
                                        <td>{{ $book->author }}</td>
                                        <td>{{ $book->bookmaker }}</td>
                                        <td>{{ $book->ed_year }}</td>

                                        @if(isExtant($book->id))
                                            <td class="text-center"><span class="label label-success">موجود</span></td>
                                        @else
                                            <td class="text-center"><span class="label label-danger">ناموجود</span></td>
                                        @endif
                                        <td class="text-center">
                                            <a href="{{ route('books.show', ['book' => $book->id]) }}" title="مشاهده" data-toggle="tooltip" class="btn btn-effect-ripple btn-xs btn-success" style="overflow: hidden; position: relative;"><i class="fa fa-eye"></i></a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- END Row Styles Content -->
                </div>
                <!-- END Row Styles Block -->

            </div>
        </div>
    @endif
@endsection

resources/views/admin/book/search.blade.php
@extends('admin.layouts.master', ['title' => 'جستجوس کتاب'])

@section('content')

    <!-- Search Results Header -->
    <div class="content-header">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <div class="header-section">
                    <form id="form-validation">
                        <div class="form-group">
                            <input id="search" type="text"  name="search" class="form-control" placeholder="عبارت جستجو" value="{{{ request('search') }}}" >
                        </div>

                        <div class="text-center">
                            <button type="submit" class="btn btn-effect-ripple btn-effect-ripple btn-primary">جستجو کن</button> <i id="wait" class="fa fa-spinner fa-1x fa-spin text-primary hidden"></i>
                        </div>
                    </form>

                </div>
                @include('admin.layouts.messages')
            </div>
        </div>
    </div>
    <!-- END Search Results Header -->

        <!-- Tables Row -->
        <div id="results" class="col-lg-12 hidden">
            <!-- Row Styles Block -->
            <div class="block">
                <!-- Row Styles Content -->
                <div class="table-responsive">
                    <table id="results_table" class="table table-borderless table-vcenter table-hover">
                        <thead>
                        <tr>
                            <th class="text-center" style="width: 50px;">ID</th>
                            <th>نام کتاب</th>
                            <th>نویسنده</th>
                            <th>دسته بندی</th>
                            <th>ناشر</th>
                            <th>سال چاپ</th>
                            <th class="text-center">وضعیت</th>

                            @can('books-admin') <script>var admin = 1;</script> <th style="width: 80px;" class="text-center"><i class="fa fa-flash"></i></th> @endcan
                        </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
                <!-- END Row Styles Content -->
            </div>
            <!-- END Row Styles Block -->
        </div>
    <!-- END Tables Row -->

    <div id="noResult" class="block full hidden">
        <!-- Get Started Content -->
        نتیجه ای یافت نشد!
        <!-- END Get Started Content -->
    </div>

@endsection

@section('scripts')
    <script src="/js/pages/book-search.js"></script>
@endsection

resources/views/admin/book/show.blade.php
@extends('admin.layouts.master', ['title' => 'اطلاعات کتاب'])

@section('content')

    <div class="row">
        <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
            <!-- Form Validation Block -->
            <div class="block">
                <!-- Form Validation Title -->
                <div class="block-title">
                    <h2>اطلاعات کتاب {{ $book->name }}</h2>
                </div>
                <!-- END Form Validation Title -->

                <!-- Form Validation Form -->
                <form id="form-validation" method="post" class="form-horizontal form-bordered">

                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">نام کتاب : </label>
                        <div class="col-md-6">
                            <p class="form-control-static">{{ $book->name }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">نویسنده : </label>
                        <div class="col-md-6">
                            <p class="form-control-static">{{ $book->author }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">ناشر : </label>
                        <div class="col-md-6">
                            <p class="form-control-static">{{ $book->bookmaker }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">تاریخ ثبت : </label>
                        <div class="col-md-6">
                            <p class="form-control-static">@jalali($book->created_at)</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">تعداد : </label>
                        <div class="col-md-6">
                            <p class="form-control-static">{{ $book->count }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">سال چاپ : </label>
                        <div class="col-md-6">
                            <p class="form-control-static">{{ $book->ed_year }}</p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">توضیحات : </label>
                        <div class="col-md-6">
                            <p class="form-control-static">{{ $book->description }}</p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">دسته بندی : </label>
                        <div class="col-md-6">
                            <p class="form-control-static label label-default">{{ $book->category->name }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">اضافه شده توسط : </label>
                        <div class="col-md-6">
                            @can('users-admin') <p class="form-control-static"><a href="{{ route('users.show', ['user' => $book->user->id]) }}" target="_blank">{{ $book->user->fullName }} <i class="gi gi-new_window"></i></a></p> @endcan
                            @cannot('users-admin') <p class="form-control-static">{{ $book->user->fullName }}</p> @endcannot
                        </div>
                    </div>

                    <div class="form-group form-actions">
                        <div class="col-md-12 col-md-offset-1">
                            <a href="{{ route('books.edit', ['book' => $book->id]) }}"><button type="button" class="btn btn-effect-ripple btn-success" style="overflow: hidden; position: relative;"><i class="fa fa-edit"></i> ویرایش</button></a>
                            <button onclick="newWindow = window.open('{{ asset(barcode($book->id)) }}');newWindow.print();" type="button" class="btn btn-effect-ripple btn-warning" style="overflow: hidden; position: relative;"><i class="fa fa-print"></i> چاپ بارکد</button>
                            <a href="#modal-fade" data-toggle="modal" title="حذف"><button type="button" class="btn btn-effect-ripple btn-danger" style="overflow: hidden; position: relative;"><i class="fa fa-trash-o"></i> حذف کتاب</button></a>

                        </div>
                    </div>
                </form>
                <!-- END Form Validation Form -->

                    <form id="delete-book-form" action="{{ route('books.destroy', ['book' => $book->id]) }}" method="post">
                        {!! csrf_field() !!}
                        {{ method_field('DELETE') }}
                    </form>

                <div id="modal-fade" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                <h3 class="modal-title"><strong>هشدار</strong></h3>
                            </div>
                            <div class="modal-body">
                                با حذف کتاب تمامی داده های مربوط به آن نیز پاک خواهد شد،آیا میخواهید کتاب را حذف کنید؟
                            </div>
                            <div class="modal-footer">
                                <button onclick="document.getElementById('delete-book-form').submit();" type="button" class="btn btn-effect-ripple btn-danger" style="overflow: hidden; position: relative;">به هر حال حذف شود</button></a>
                                <button type="button" class="btn btn-effect-ripple btn-success" data-dismiss="modal" style="overflow: hidden; position: relative;">خیر</button>
                            </div>
                        </div>
                    </div>
                </div>


            </div>
            <!-- END Form Validation Block -->
        </div>
    </div>
@endsection