routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', 'HomeController@index')->middleware('guest');
Route::get('faq', 'HomeController@faq')->name('faq');

Route::get('article/{article}', 'HomeController@show')->name('article.show');
Route::post('article/{article}/comment', 'CommentController@store')->middleware('auth')->name('comment.store');

Route::group(['prefix' => 'admin', 'middleware' => 'checkAdmin'], function () {
    Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
    Route::get('settings', 'HomeController@settings')->name('settings')->middleware('can:settings-admin');
    Route::get('statistics', 'HomeController@statistics')->name('statistics');
    Route::post('settings', 'HomeController@settingsStore')->name('settings.store')->middleware('can:settings-admin');

    Route::resource('roles' , 'RoleController');
    Route::resource('books', 'BookController');
    Route::get('book-categories', 'BookCategoryController@index')->name('book-categories.index');
    Route::post('book-categories', 'BookCategoryController@store')->name('book-categories.store');
    Route::delete('book-categories', 'BookCategoryController@destroy')->name('book-categories.destroy');
    Route::patch('book-categories', 'BookCategoryController@update')->name('book-categories.update');
    Route::resource('articles', 'ArticleController');
    Route::get('articles/comments/index', 'ArticleController@comments')->name('articles.comments');
    Route::resource('users', 'UserController');

    Route::group(['prefix' => 'users'], function () {
        Route::get('new/index', 'UserController@newUsers')->name('users.new');
        Route::get('{user}/confirm', 'UserController@confirm')->name('users.confirm');
    });

    Route::get('user-search', 'UserController@search')->name('users.search');

    Route::group(['prefix' => 'lends', 'middleware' => 'can:lends-admin'], function () {
        Route::get('admin', 'LendController@admin')->name('lends.admin');
        Route::post('user-active-lends', 'LendController@userActiveLends')->name('lends.userActiveLends');
        Route::get('{user}/lends-history', 'LendController@lendsHistory')->name('users.lendsHistory');
        Route::get('{user}/active-lends', 'LendController@activeLends')->name('users.activeLends');
        Route::get('all-active-lends', 'LendController@allActiveLends')->name('lends.allActiveLends');

        Route::post('create', 'LendController@create')->name('lends.create');
        Route::get('extend/{lend}', 'LendController@extendLend')->name('lends.extend');
        Route::get('return/{lend}', 'LendController@returnLend')->name('lends.return');
    });
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth:web'], function () {
    Route::get('profile', 'HomeController@profile')->name('profile');
    Route::get('lends/my-active-lends', 'HomeController@myActiveLends')->name('lends.myActiveLends');
    Route::get('lends/my-lends-history', 'HomeController@myLendsHistory')->name('lends.myLendsHistory');
    Route::get('lends/extend-my-lend/{lend}', 'HomeController@extendMyLend')->name('lends.extendMyLend');
    Route::get('faq', 'HomeController@faq_admin')->name('admin-faq');

    Route::get('book-search', 'HomeController@bookSearch')->name('books.search');
});

app/User.php
<?php

namespace App;

use Creativeorange\Gravatar\Facades\Gravatar;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function books()
    {
        return $this->hasMany(Book::class);
    }

    public function lends()
    {
        return $this->hasMany(Lend::class);
    }

    public function articles()
    {
        return $this->hasMany(Article::class);
    }

    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    public function hasRole($role)
    {
        if (is_string($role)) {
            return $this->roles->contains('name', $role);
        }

        return $role->intersect($this->roles)->count();
    }

    public function getFullNameAttribute()
    {
        return "{$this->firstName} {$this->lastName}";
    }

    public function getCreatedAtAttribute($value)
    {
        return jDate($value)->format('%d %B %Y');
    }

    public function getGetImageAttribute()
    {
        $value = $this->image;

        if ($value != 'default.jpg') {
            return asset('user-img/' . $value);
        }

        if (Gravatar::exists($this->email)) {
            return Gravatar::get($this->email);
        }

        return asset('img/placeholders/avatars/' . $value);
    }

    public function isAdmin()
    {
        return $this->level == 'admin' || $this->level == 'creator' ? true : false;
    }

    public function scopeSearch($query, $keyword)
    {

        $query->WhereRaw("concat(firstName, ' ', lastName) like '%{$keyword}%' ");
        return $query;
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

resources/views/admin/dashboard.blade.php
@extends('admin.layouts.master', ['title' => 'داشبورد'])

@section('content')

    <div class="row">

        <div class="col-sm-6 col-lg-3">
            <a class="widget" href="{{ route('users.index') }}">
                <div class="widget-content widget-content-mini text-right clearfix">
                    <div class="widget-icon pull-left themed-background-info">
                        <i class="gi gi-user text-light-op"></i>
                    </div>
                    <h2 class="widget-heading h3 text-info">
                        <strong><span data-toggle="counter" data-to="{{ $users_count }}"></span></strong>
                    </h2>
                    <span class="text-muted">کاربران</span>
                </div>
            </a>
        </div>
        <div class="col-sm-6 col-lg-3">
            <a class="widget" href="{{ route('books.index') }}">
                <div class="widget-content widget-content-mini text-right clearfix">
                    <div class="widget-icon pull-left themed-background-success">
                        <i class="gi gi-book text-light-op"></i>
                    </div>
                    <h2 class="widget-heading h3 text-success">
                        <strong><span data-toggle="counter" data-to="{{ $books_count }}"></span></strong>
                    </h2>
                    <span class="text-muted">کتاب ها</span>
                </div>
            </a>
        </div>
        <div class="col-sm-6 col-lg-3">
            <a class="widget" href="{{ route('lends.allActiveLends') }}">
                <div class="widget-content widget-content-mini text-right clearfix">
                    <div class="widget-icon pull-left themed-background-warning">
                        <i class="hi hi-log_out text-light-op"></i>
                    </div>
                    <h2 class="widget-heading h3 text-warning">
                        <strong><span data-toggle="counter" data-to="{{ $active_lends_count }}"></span></strong>
                    </h2>
                    <span class="text-muted">امانت های جاری</span>
                </div>
            </a>
        </div>
        <div class="col-sm-6 col-lg-3">
            <a href="{{ route('articles.comments') }}" class="widget">
                <div class="widget-content widget-content-mini text-right clearfix">
                    <div class="widget-icon pull-left themed-background-danger">
                        <i class="gi gi-conversation text-light-op"></i>
                    </div>
                    <h2 class="widget-heading h3 text-danger">
                        <strong><span data-toggle="counter" data-to="{{ $comments_count }}"></span></strong>
                    </h2>
                    <span class="text-muted">مجموع نظرات ها</span>
                </div>
            </a>
        </div>

        @if(count($last_articles))
            <div class="col-sm-12 col-lg-6">
                <!-- Tickets Block -->
                <div class="block">
                    <div class="block-title">
                        <h2>آخرین نوشته های وبلاگ</h2>
                        <div class="block-options pull-right">
                            <a href="{{ route('articles.index') }}" class="btn btn-effect-ripple btn-default" data-toggle="tooltip" title="مشاهده همه"><i class="hi hi-circle-arrow-left"></i></a>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <table class="table table-borderless table-vcenter table-hover">
                            <thead>
                                <tr>
                                    <th>عنوان</th>
                                    <th class="text-center">وضعیت</th>
                                    <th class="text-center">تاریخ انتشار</th>
                                    <th class="text-center"><i class="fa fa-comments"></i></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($last_articles as $article)
                                    <tr>
                                        <td><a href="{{ route('article.show', ['article' => $article->slug]) }}" target="_blank"><strong>{{ $article->title }}</strong></a></td>

                                        @if($article->status == 'publish')
                                            <td class="text-center"><span class="label label-success">منتشر شده</span></td>
                                        @else
                                            <td class="text-center"><span class="label label-danger">پیش نویس</span></td>
                                        @endif

                                        <td class="text-center">{{ $article->created_at }}</td>

                                        <td class="text-center"><span class="badge">{{ $article->comments->count() }}</span></td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- END Tickets List -->
            </div>
        @endif

        @if(count($last_comments))
            <div class="col-sm-12 col-lg-6">
                <!-- latest comments Block -->
                <div class="block">
                    <div class="block-title">
                        <h2>آخرین دیدگاه ها</h2>
                        <div class="block-options pull-right">
                            <a href="{{ route('articles.comments') }}" class="btn btn-effect-ripple btn-default" data-toggle="tooltip" title="مشاهده همه"><i class="hi hi-circle-arrow-left"></i></a>
                        </div>
                    </div>
                    <div class="widget-content">
                        <ul class="media-list">
                            @foreach($last_comments as $comment)
                                <li class="media">
                                    <a target="_blank" @can('users-admin') href="{{ route('users.show', ['user' => $comment->user->id]) }}" @endcan class="pull-left">
                                        <img style="width: 40px;height: 40px;" src="{{ $comment->user->getImage }}" alt="{{ $comment->user->fullName }}" class="img-circle">
                                    </a>
                                    <div class="media-body">
                                        <span class="text-muted pull-right"><small><em>{{ jdate($comment->created_at)->ago() }}</em></small></span>
                                        <small><a target="_blank" @can('users-admin') href="{{ route('users.show', ['user' => $comment->user->id]) }}" @endcan>{{ $comment->user->fullname }}</a> در <a target="_blank" href="{{ route('article.show', ['article' => $comment->article->slug]) }}">{{ $comment->article->title }}</a></small>

                                        @php
                                            $string = $comment->body;
                                            $string = strip_tags($string);
                                            if (strlen($string) > 300) {
                                                // truncate string
                                                $stringCut = substr($string, 0, 250);
                                                $endPoint = strrpos($stringCut, ' ');

                                                //if the string doesn't contain any space then it will cut without word basis.
                                                $string = $endPoint? substr($stringCut, 0, $endPoint):substr($stringCut, 0);
                                                $string .= '...';
                                            }
                                        @endphp

                                        <p>{{ $string }}</p>
                                    </div>
                                </li>
                            @endforeach
                        </ul>
                    </div>
                </div>
                <!-- END latest comments block -->
            </div>
        @endif

    </div>

@endsection

@section('scripts')
    <script src="/js/pages/readyDashboard.js"></script>
    <script>$(function(){ ReadyDashboard.init(); });</script>
@endsection

resources/views/admin/faq.blade.php
@extends('admin.layouts.master', ['title' => 'سوالات متداول'])

@section('content')

    <!-- Intro Block -->
    <div class="block">
        <!-- Intro Title -->
        <div class="block-title">
            <h2>درباره نرم افزار</h2>
        </div>
        <!-- END Intro Title -->

        <!-- Intro Content -->
        <div id="faq1" class="panel-group">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-title">
                        <i class="fa fa-angle-left"></i> <a class="accordion-toggle" data-toggle="collapse" data-parent="#faq1" href="#faq1_q1"><strong>به سیستم کتابخانه دیجیتال خوش آمدید</strong></a>
                    </div>
                </div>
                <div id="faq1_q1" class="panel-collapse collapse in">
                    <div class="panel-body">
                        <p>در اینجا توضیحات مربوط به نرم افزار قرار میگیرد</p>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-title">
                        <i class="fa fa-angle-left"></i> <a class="accordion-toggle" data-toggle="collapse" data-parent="#faq1" href="#faq1_q2"><strong>توسعه دهنده نرم افزار چه کسی است؟</strong></a>
                    </div>
                </div>
                <div id="faq1_q2" class="panel-collapse collapse">
                    <div class="panel-body">
                        <p>بلی بلی</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- END Intro Content -->
    </div>
    <!-- END Intro Block -->

    <!-- Functionality Block -->
    <div class="block">
        <!-- Functionality Title -->
        <div class="block-title">
            <h2>عملکرد</h2>
        </div>
        <!-- END Functionality Title -->

        <!-- Functionality Content -->
        <div id="faq2" class="panel-group">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-title">
                        <i class="fa fa-angle-left"></i> <a class="accordion-toggle" data-toggle="collapse" data-parent="#faq2" href="#faq2_q1"><strong>آیا نرم افزار شما واکنشگراست؟</strong></a>
                    </div>
                </div>
                <div id="faq2_q1" class="panel-collapse collapse">
                    <div class="panel-body">بدون شک نرم افزار ما در تمامی مرورگرها عملکرد خوبی خواهد داشت!!</div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-title">
                        <i class="fa fa-angle-left"></i> <a class="accordion-toggle" data-toggle="collapse" data-parent="#faq2" href="#faq2_q2"><strong>آیا داده ها در این نرم افزار به صورت امن ارسال و دریافت می شوند؟</strong></a>
                    </div>
                </div>
                <div id="faq2_q2" class="panel-collapse collapse">
                    <div class="panel-body">تا دلت بخواد :)</div>
                </div>
            </div>
        </div>
        <!-- END Functionality Content -->
    </div>
    <!-- END Functionality Block -->

@endsection

resources/views/admin/profile.blade.php
@extends('admin.layouts.master', ['title' => 'پروفایل'])

@section('content')

    <div class="row">
        <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">

            <div class="block">
                <!-- General Elements Title -->
                <div class="block-title">
                    <h2>پروفایل کاربری من</h2>
                </div>

                <!-- END General Elements Title -->

                <!-- General Elements Content -->
                <form method="post" class="form-horizontal form-bordered">
                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">تصویر پروفایل : </label>
                        <div class="col-md-7">
                            <div class="widget">
                                <img src="{{ $user->getImage }}" style="border-radius: 10px;width:100px;height:100px;" alt="avatar" class="img-circle">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">نام : </label>
                        <div class="col-md-7">
                            <p class="form-control-static">{{ $user->firstName }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">نام خانوادگی : </label>
                        <div class="col-md-7">
                            <p class="form-control-static">{{ $user->lastName }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">کد ملی (نام کاربری) : </label>
                        <div class="col-md-7">
                            <p class="form-control-static">{{ $user->username }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">تاریخ عضویت : </label>
                        <div class="col-md-7">
                            <p class="form-control-static">{{ $user->created_at }}</p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">تلفن : </label>
                        <div class="col-md-7">
                            <p class="form-control-static">{{ $user->tel }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">ایمیل : </label>
                        <div class="col-md-7">
                            <p class="form-control-static">{{ $user->email }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">آدرس : </label>
                        <div class="col-md-7">
                            <p class="form-control-static">{{ $user->address }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">درباره من : </label>
                        <div class="col-md-7">
                            <p class="form-control-static">{{ $user->status }}</p>
                        </div>
                    </div>

                </form>
                <!-- END General Elements Content -->
            </div>
        </div>
    </div>

@endsection

resources/views/admin/settings.blade.php
@extends('admin.layouts.master', ['title' => 'تنظیمات'])

@section('content')

    <!-- Form Validation Content -->
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
            <!-- Form Validation Block -->
            <div class="block">
                <!-- Form Validation Title -->
                <div class="block-title">
                    <h2>تنظیمات</h2>
                </div>
                <!-- END Form Validation Title -->

                <!-- Form Validation Form -->
                <form action="{{ route('settings.store') }}" id="form-validation" method="post" class="form-horizontal form-bordered">
                    {!! csrf_field() !!}

                    <div class="form-group">
                        <label class="col-md-5 control-label">دوره تمدید کاربر (روز)</label>
                        <div class="col-md-6">
                            <input type="number" max="365" min="14" id="user-active-period" name="user-active-period" class="form-control " value="{{ option('userActivePeriod', 365) }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-5 control-label">دوره امانت (روز)</label>
                        <div class="col-md-6">
                            <input type="number" max="30" min="7" name="lend-period" class="form-control " value="{{ option('lendPeriod', 14) }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-5 control-label">حداکثر امانت جاری</label>
                        <div class="col-md-6">
                            <input type="number" max="10" min="1" name="max-active-lend" class="form-control " value="{{ option('maxActiveLend', 3) }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-5 control-label">تعداد تمدید مجاز</label>
                        <div class="col-md-6">
                            <input type="number" max="5" min="1" name="max-extend-count" class="form-control " value="{{ option('maxExtendCount', 1) }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-5 control-label">فعال کردن صفحه ثبت نام کاربران</label>
                        <div class="col-md-6">
                            <label class="switch switch-primary"><input type="checkbox" name="user-register" @if(option('userRegister', 'off') == 'on') checked @endif><span></span></label>
                        </div>
                    </div>

                    <div class="form-group form-actions">
                        <div class="col-md-6 col-md-offset-5">
                            <button type="submit" class="btn btn-effect-ripple btn-primary" style="overflow: hidden; position: relative;">ذخیره تنظیمات</button>
                        </div>
                    </div>
                </form>
                <!-- END Form Validation Form -->

            </div>
            <!-- END Form Validation Block -->
            @include('admin.layouts.errors')
            @include('admin.layouts.messages')
        </div>

    </div>
    <!-- END Form Validation Content -->

@endsection

resources/views/admin/statistics.blade.php
@extends('admin.layouts.master', ['title' => 'آمار'])

@section('content')

    <div class="block full">
        <!-- Get Started Title -->
        <div class="block-title">
            <h2>آمار سایت</h2>
        </div>
        <!-- END Get Started Title -->

        <!-- Get Started Content -->
        در اینجا آمار وبسایت نشان داده خواهد شد.
        در دست ساخت :)
        <!-- END Get Started Content -->
    </div>

@endsection