routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', 'HomeController@index')->middleware('guest');
Route::get('faq', 'HomeController@faq')->name('faq');

Route::get('article/{article}', 'HomeController@show')->name('article.show');
Route::post('article/{article}/comment', 'CommentController@store')->middleware('auth')->name('comment.store');

Route::group(['prefix' => 'admin', 'middleware' => 'checkAdmin'], function () {
    Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
    Route::get('settings', 'HomeController@settings')->name('settings')->middleware('can:settings-admin');
    Route::get('statistics', 'HomeController@statistics')->name('statistics');
    Route::post('settings', 'HomeController@settingsStore')->name('settings.store')->middleware('can:settings-admin');

    Route::resource('roles' , 'RoleController');
    Route::resource('books', 'BookController');
    Route::get('book-categories', 'BookCategoryController@index')->name('book-categories.index');
    Route::post('book-categories', 'BookCategoryController@store')->name('book-categories.store');
    Route::delete('book-categories', 'BookCategoryController@destroy')->name('book-categories.destroy');
    Route::patch('book-categories', 'BookCategoryController@update')->name('book-categories.update');
    Route::resource('articles', 'ArticleController');
    Route::get('articles/comments/index', 'ArticleController@comments')->name('articles.comments');
    Route::resource('users', 'UserController');

    Route::group(['prefix' => 'users'], function () {
        Route::get('new/index', 'UserController@newUsers')->name('users.new');
        Route::get('{user}/confirm', 'UserController@confirm')->name('users.confirm');
    });

    Route::get('user-search', 'UserController@search')->name('users.search');

    Route::group(['prefix' => 'lends', 'middleware' => 'can:lends-admin'], function () {
        Route::get('admin', 'LendController@admin')->name('lends.admin');
        Route::post('user-active-lends', 'LendController@userActiveLends')->name('lends.userActiveLends');
        Route::get('{user}/lends-history', 'LendController@lendsHistory')->name('users.lendsHistory');
        Route::get('{user}/active-lends', 'LendController@activeLends')->name('users.activeLends');
        Route::get('all-active-lends', 'LendController@allActiveLends')->name('lends.allActiveLends');

        Route::post('create', 'LendController@create')->name('lends.create');
        Route::get('extend/{lend}', 'LendController@extendLend')->name('lends.extend');
        Route::get('return/{lend}', 'LendController@returnLend')->name('lends.return');
    });
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth:web'], function () {
    Route::get('profile', 'HomeController@profile')->name('profile');
    Route::get('lends/my-active-lends', 'HomeController@myActiveLends')->name('lends.myActiveLends');
    Route::get('lends/my-lends-history', 'HomeController@myLendsHistory')->name('lends.myLendsHistory');
    Route::get('lends/extend-my-lend/{lend}', 'HomeController@extendMyLend')->name('lends.extendMyLend');
    Route::get('faq', 'HomeController@faq_admin')->name('admin-faq');

    Route::get('book-search', 'HomeController@bookSearch')->name('books.search');
});

app/User.php
<?php

namespace App;

use Creativeorange\Gravatar\Facades\Gravatar;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function books()
    {
        return $this->hasMany(Book::class);
    }

    public function lends()
    {
        return $this->hasMany(Lend::class);
    }

    public function articles()
    {
        return $this->hasMany(Article::class);
    }

    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    public function hasRole($role)
    {
        if (is_string($role)) {
            return $this->roles->contains('name', $role);
        }

        return $role->intersect($this->roles)->count();
    }

    public function getFullNameAttribute()
    {
        return "{$this->firstName} {$this->lastName}";
    }

    public function getCreatedAtAttribute($value)
    {
        return jDate($value)->format('%d %B %Y');
    }

    public function getGetImageAttribute()
    {
        $value = $this->image;

        if ($value != 'default.jpg') {
            return asset('user-img/' . $value);
        }

        if (Gravatar::exists($this->email)) {
            return Gravatar::get($this->email);
        }

        return asset('img/placeholders/avatars/' . $value);
    }

    public function isAdmin()
    {
        return $this->level == 'admin' || $this->level == 'creator' ? true : false;
    }

    public function scopeSearch($query, $keyword)
    {

        $query->WhereRaw("concat(firstName, ' ', lastName) like '%{$keyword}%' ");
        return $query;
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRequest;
use App\Role;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Gate;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:users-admin');
    }

    public function index()
    {
        $users = User::where('level', '!=', 'new')->get();
        return view('admin.user.index', compact('users'));
    }

    public function newUsers()
    {
        $users = User::where('level', 'new')->get();

        return view('admin.user.new', compact('users'));
    }

    public function confirm(User $user)
    {
        if ($user->level != 'new') {
            abort(404);
        }

        $user->update([
            'level' => 'user',
        ]);

        session()->flash('message', 'عملیات با موفقیت انجام شد');

        return back();
    }

    public function create()
    {
        return view('admin.user.create');
    }

    public function edit(User $user)
    {
        $roles = Role::all();
        return view('admin.user.edit', compact('user', 'roles'));
    }

    public function update(User $user)
    {
        $this->validate(request(), [
            'file' => 'file|image|mimes:jpeg|max:500',
            'first-name' => 'required',
            'last-name' => 'required',
            'email' => 'nullable|Email|unique:users,email,' . $user->id,
            'national-code' => 'required|unique:users,username,' . $user->id,
            'tel' => 'required',
            'address' => 'required',

        ], [
            'file.required' => 'لطفا فایل تصویر را انتخاب کنید',
            'file.file' => 'لطفا فایلی را برای ارسال انتخاب کنید',
            'file.image' => 'لطفا یک فایل عکس انتخاب کنید',
            'file.mimes' => 'لطفا عکس با فرمت jpeg ارسال کنید',
            'file.max' => 'اندازه ی فایل ارسالی نباید بیشتر از 500 کیلوبایت باشد',

            'first-name.required' => 'لطفا نام کاربر را وارد کنید',
            'last-name.required' => 'لطفا نام خانوادگی کاربر را وارد کنید',
            'email.email' => 'لطفا ایمیل کاربر را به درستی وارد کنید',
            'email.unique' => 'ایمیل وارد شده از قبل در سیستم موجود است',
            'national-code.required' => 'لطفا کد ملی کاربر را وارد کنید',
            'national-code.unique' => 'کد ملی وارد شده از قبل در سیستم موجود است',
            'tel.required' => 'لطفا شماره تلفن کاربر را وارد کنید',
            'address.required' => 'لطفا آدرس کاربر را وارد کنید',

        ]);

        if (request('file')) {
            if ($user->image == 'default.jpg') {
                do {
                    $randomString = str_random(20) . '.jpg';
                    $user_image = User::where('image', $randomString)->get();

                } while (!$user_image->isEmpty());

                $user->update([
                    'image' => $randomString,
                ]);

                request('file')
                    ->move(public_path('user-img'), $randomString);

            } else {
                $randomString = $user->image;

                request('file')
                    ->move(public_path('user-img'), $randomString);
            }
        }

        if ($user->level != 'creator' && Gate::allows('roles-admin')) {
            $this->validate(request(), [
                'role_id' => 'exists:roles,id',
            ], [
                'role_id.exists' => 'آیدی مقام در پایگاه داده یافت نشد',
            ]);

            if (request('role_id')) {
                $user->level = 'admin';
            } else {
                $user->level = 'user';
            }

            $user->roles()->sync(request()->input('role_id'));
        }

        $user->update([
            'firstName' => request('first-name'),
            'lastName' => request('last-name'),
            'tel' => request('tel'),
            'address' => request('address'),
        ]);

        session()->flash('message', 'اطلاعات کاربر با موفقیت بروزرسانی شد.');

        return redirect(route('users.index'));

    }

    public function destroy(User $user)
    {
        if ($user->level == 'creator') {
            abort(404);
        }

        if ($user->level == 'admin' && auth()->user()->level == 'admin') {
            abort(404);
        }

        if ($user->image != 'default.jpg') {
            File::delete(public_path('user-img/' . $user->image));
        }

        $level = $user->level;

        $user->delete();

        session()->flash('message', 'کاربر با موفقیت حذف شد');

        if($level == 'new') {
            return redirect(route('users.new'));
        }

        return redirect(route('users.index'));
    }

    public function show(User $user)
    {
        return view('admin.user.show', compact('user'));
    }

    public function store(Request $request)
    {
        $this->validate(request(), [
            'first-name' => 'required',
            'last-name' => 'required',
            'email' => 'nullable|Email|unique:users',
            'national-code' => 'required|unique:users,username',
            'tel' => 'required',
            'address' => 'required',

        ], [
            'first-name.required' => 'لطفا نام کاربر را وارد کنید',
            'last-name.required' => 'لطفا نام خانوادگی کاربر را وارد کنید',
            'email.email' => 'لطفا ایمیل کاربر را به درستی وارد کنید',
            'email.unique' => 'ایمیل وارد شده از قبل در سیستم موجود است',
            'national-code.required' => 'لطفا کد ملی کاربر را وارد کنید',
            'national-code.unique' => 'کد ملی وارد شده از قبل در سیستم موجود است',

            'tel.required' => 'لطفا شماره تلفن کاربر را وارد کنید',
            'address.required' => 'لطفا آدرس کاربر را وارد کنید',
        ]);

        User::create([
            'username' => request('national-code'),
            'firstName' => request('first-name'),
            'lastName' => request('last-name'),
            'email' => request('email'),
            'tel' => request('tel'),
            'address' => request('address'),
            'password' => bcrypt(request('national-code')),
            'level' => 'user',
        ]);

        session()->flash('message', 'کاربر با موفقیت اضافه شد');

        return back();
    }

    public function search()
    {
        if (!request('search')) {
            $usersChunk = [];
            return view('admin.user.search', compact('usersChunk'));
        } else {
            $users = User::search(request('search'))->get();
            $usersChunk = $users->chunk(1);
            return view('admin.user.search', compact('usersChunk'));
        }
    }
}

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.master', ['title' => 'ویرایش کاربر'])

@section('content')

    <!-- Form Validation Content -->
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">

            @include('admin.layouts.errors')
            @include('admin.layouts.messages')

            <!-- Form Validation Block -->
            <div class="block">
                <!-- Form Validation Title -->
                <div class="block-title">
                    <h2>ویرایش اطلاعات کاربر</h2>
                </div>
                <!-- END Form Validation Title -->

                <!-- Form Validation Form -->
                <form action="{{ route('users.update', ['user' => $user->id]) }}" id="form-validation" method="post" enctype="multipart/form-data" class="form-horizontal form-bordered">
                    {!! csrf_field() !!}
                    {{ method_field('PATCH') }}

                    <div class="form-group">
                        <label class="col-md-3 control-label">تصویر فعلی : </label>
                        <div class="col-md-8">
                            <div class="widget">
                                <img src="{{ $user->getImage }}" style="border-radius: 10px;width:100px;height:100px;" alt="avatar" class="img-circle">
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="file">تصویر جدید </label>
                        <div class="col-md-9">
                            <input type="file" id="file" name="file">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label"> </label>
                        <div class="col-md-9">
                            <p class="well well-sm"><strong>نکته : </strong><br>تصویر کاربر باید با فرمت jpeg با حجم کمتر از 500 کیلوبایت باشد.<br><small>( بهترین اندازه 128*128 )</small></p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="val-first-name">نام <span class="text-danger">*</span></label>
                        <div class="col-md-6">
                            <input type="text" id="val-first-name" name="first-name" class="form-control" value="{{ $user->firstName }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="val-last-name">نام خانوادگی <span class="text-danger">*</span></label>
                        <div class="col-md-6">
                            <input type="text" id="val-last-name" name="last-name" class="form-control" value="{{ $user->lastName }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="val-email">ایمیل </label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" id="val-email" name="email" value="{{ $user->email }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="val-national-code">کد ملی <span class="text-danger">*</span></label>
                        <div class="col-md-6">
                            <input type="text" id="val-national-code" name="national-code" class="form-control" value="{{ $user->username }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="val-tel">شماره تلفن <span class="text-danger">*</span></label>
                        <div class="col-md-6">
                            <input type="text" id="val-tel" name="tel" class="form-control" value="{{ $user->tel }}">
                        </div>
                    </div>

                    @if($user->level != 'creator')
                        @can('roles-admin')
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="role_id">مقام ها </label>
                                <div class="col-md-6">
                                    <select id="role_id" name="role_id[]" class="select-chosen" data-placeholder="انتخاب کنید.." style="width: 250px;" multiple>
                                        @foreach($roles as $role)
                                            <option value="{{ $role->id }}" {{ $user->hasRole($role->name) ? 'selected' : '' }}>{{ $role->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        @endcan
                    @endif

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="val-address">آدرس <span class="text-danger">*</span></label>
                        <div class="col-md-9">
                            <textarea id="val-address" name="address" rows="7" class="form-control">{{ $user->address }}</textarea>
                        </div>
                    </div>

                    <div class="form-group form-actions">
                        <div class="col-md-8 col-md-offset-3">
                            <button type="submit" name="submit" class="btn btn-effect-ripple btn-primary" style="overflow: hidden; position: relative;">ذخیره</button>
                            <a href="{{ route('users.show', ['user' => $user->id]) }}"><button type="button" class="btn btn-effect-ripple btn-warning" style="overflow: hidden; position: relative;"><i class="gi gi-redo"></i> بازگشت به صفحه پروفایل </button></a>
                        </div>
                    </div>
                </form>
                <!-- END Form Validation Form -->

            </div>			<!-- END Form Validation Block -->
        </div>
    </div>
    <!-- END Form Validation Content -->

@endsection

@section('scripts')
    <script src="/js/pages/userEdit.js"></script>
    <script>$(function(){ FormsValidation.init(); });</script>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.master', ['title' => 'لیست کاربران'])

@section('content')

    <!-- Page Header -->
    <div class="content-header">
        <div class="row">
            <div class="col-sm-6">
                <div class="header-section">
                    <h1>لیست کاربران</h1>
                </div>
            </div>
            <div class="col-sm-6 hidden-xs">
                <div class="header-section">
                    <ul class="breadcrumb breadcrumb-top">
                        <li>مدیریت کاربران</li>
                        <li>لیست کاربران</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- END Page Header -->

    @if(! $users->count())

        <div class="block full">
            <!-- Get Started Content -->
            لیست کاربران خالی است.
            <!-- END Get Started Content -->
        </div>

    @else

        <div class="row">
            <!-- Tables Row -->
            <div class="col-lg-12">
                @include('admin.layouts.messages')

                <!-- Row Styles Block -->
                <div class="block">
                    <!-- Row Styles Content -->
                    <div class="table-responsive">
                        <table class="table table-borderless table-vcenter table-hover">
                            <thead>
                                <tr>
                                    <th class="text-center" style="width: 50px;">ID</th>
                                    <th>نام</th>
                                    <th>نام خانوادگی</th>
                                    <th>کد ملی</th>
                                    <th>تاریخ عضویت</th>
                                    <th style="width: 80px;" class="text-center"><i class="fa fa-flash"></i></th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <td class="text-center"><strong>{{ $user->id }}</strong></td>
                                    <td>{{ $user->firstName }}</td>
                                    <td>{{ $user->lastName }}</td>
                                    <td>{{ $user->username }}</td>
                                    <td>{{ $user->created_at }}</td>
                                    <td class="text-center">
                                        <a href="{{ route('users.show', ['user' => $user->id]) }}" data-toggle="tooltip" title="مشاهده" class="btn btn-effect-ripple btn-xs btn-success" style="overflow: hidden; position: relative;"><i class="fa fa-eye"></i></a>
                                    </td>
                                </tr>
                            @endforeach

                            </tbody>
                        </table>
                    </div>
                    <!-- END Row Styles Content -->
                </div>
                <!-- END Row Styles Block -->
            </div>
        </div>
    @endif

@endsection

resources/views/admin/user/show.blade.php
@extends('admin.layouts.master', ['title' => 'اطلاعات کاربر'])

@section('content')

    <div class="row">
        <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
            <div class="block">
                <!-- General Elements Title -->
                <div class="block-title">
                    <h2>پروفایل کاربری {{ $user->fullname }}</h2>
                </div>
                <!-- END General Elements Title -->

                <!-- General Elements Content -->
                <form method="post" class="form-horizontal form-bordered">
                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">تصویر پروفایل : </label>
                        <div class="col-md-7">
                            <div class="widget">
                                <img src="{{ $user->getImage }}" style="border-radius: 10px;width:100px;height:100px;" alt="avatar" class="img-circle">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">نام : </label>
                        <div class="col-md-7">
                            <p class="form-control-static">{{ $user->firstName }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">نام خانوادگی : </label>
                        <div class="col-md-7">
                            <p class="form-control-static">{{ $user->lastName }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">کد ملی (نام کاربری) : </label>
                        <div class="col-md-7">
                            <p class="form-control-static">{{ $user->username }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">شناسه : </label>
                        <div class="col-md-7">
                            <p class="form-control-static">{{ $user->id }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">تاریخ عضویت : </label>
                        <div class="col-md-7">
                            <p class="form-control-static">{{$user->created_at}}</p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">تلفن : </label>
                        <div class="col-md-7">
                            <p class="form-control-static">{{ $user->tel }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">ایمیل : </label>
                        <div class="col-md-7">
                            <p class="form-control-static">{{ $user->email }}</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-md-offset-1">آدرس : </label>
                        <div class="col-md-7">
                            <p class="form-control-static">{{ $user->address }}</p>
                        </div>
                    </div>
                    @can('roles-admin')
                        <div class="form-group">
                            <label class="col-md-4 col-md-offset-1">نقش : </label>
                            <div class="col-md-7">
                                <p class="form-control-static">
                                    @if($user->level == 'creator')
                                        سازنده سایت
                                    @elseif($user->level == 'admin')
                                        مدیر
                                    @else
                                        کاربر
                                    @endif
                                </p>
                            </div>
                        </div>
                        @if($user->level == 'admin')
                            <div class="form-group">
                                <label class="col-md-4 col-md-offset-1">مقام ها : </label>
                                <div class="col-md-7">
                                    <p class="form-control-static">
                                        @foreach($user->roles as $role)
                                            <span class="label label-default">{{ $role->name }}</span>
                                        @endforeach
                                    </p>
                                </div>
                            </div>
                        @endif
                    @endcan
                    <div class="form-group form-actions">
                        <div class="col-md-12 col-md-offset-1">
                            @can('lends-admin')
                                <a href="{{ route('users.activeLends', ['user' => $user->id]) }}"><button type="button" class="btn btn-effect-ripple btn-primary" style="overflow: hidden; position: relative;">امنت های جاری</button></a>
                                <a href="{{ route('users.lendsHistory', ['user' => $user->id]) }}"><button type="button" class="btn btn-effect-ripple btn-info" style="overflow: hidden; position: relative;">سابقه امانت</button></a>
                            @endcan

                            <a href="{{ route('users.edit', ['user' => $user->id]) }}"><button type="button" class="btn btn-effect-ripple btn-success" style="overflow: hidden; position: relative;"><i class="fa fa-edit"></i> ویرایش</button></a>

                            @if(can_delete_user($user->id))
                                    <a href="#modal-fade" data-toggle="modal" title="حذف"><button type="button" class="btn btn-effect-ripple btn-danger" style="overflow: hidden; position: relative;"><i class="fa fa-trash-o"></i> حذف کاربر</button></a>
                            @endif
                        </div>
                    </div>

                </form>
                @if(can_delete_user($user->id))
                    <form id="delete-user-form" action="{{ route('users.destroy', ['user' => $user->id]) }}" method="post">
                        {!! csrf_field() !!}
                        {{ method_field('DELETE') }}
                    </form>
                    <div id="modal-fade" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                    <h3 class="modal-title"><strong>هشدار</strong></h3>
                                </div>
                                <div class="modal-body">
                                    با حذف کاربر تمامی داده های مربوط به آن نیز پاک خواهد شد،
                                    آیا میخواهید کاربر را حذف کنید؟
                                </div>
                                <div class="modal-footer">
                                    <button onclick="document.getElementById('delete-user-form').submit();" type="button" class="btn btn-effect-ripple btn-danger" style="overflow: hidden; position: relative;">به هر حال حذف شود</button>
                                    <button type="button" class="btn btn-effect-ripple btn-success" data-dismiss="modal" style="overflow: hidden; position: relative;">خیر</button>
                                </div>
                            </div>
                        </div>
                    </div>
                @endif
                <!-- END General Elements Content -->
            </div>
        </div>
    </div>

@endsection